/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Fri Aug 17 11:21:24 2018
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll (ref_clk_i, rst_n_i, lock_o, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
endmodule